# This is a simple placer which generates a collection of DOEs and puts them in wanted places
# The positions are given by grid coordinates using letters for X axis and digits for Y axis
mask:
    width: 10000
    height: 10000
    name: placer_example_method2

mmi1x2:
    component: mmi1x2
    settings:
        length_mmi: [11, 12]
        width_mmi: [3.6, 7.8]
    do_permutation: False

    spacing: [50., 100.]
    origin: [0., 0.]
    shape: [2, 1]

mzi2x2:
    doe_name: doe2
    component: mzi2x2
    settings:
        L0: [60, 80, 100]
        gap: [0.23, 0.234, 0.24]
    do_permutation: True

    spacing: [200., 300.]
    origin: [100., 100.]
    shape: [3, 3]
