name: Lint and Test

on:
  push:
  schedule:
      - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        git clone https://github.com/gdsfactory/gdslib.git
        bash install.sh
    - name: Test with tox
      run: tox
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 pp
